version: '3'
services:
  db:
    image: mongo:latest
    container_name: db-Strollin
    networks:
      - backend
    ports:
      - "27017:27017"
    environment:
      PORT: 27017
    command: [--auth]
    restart: 'on-failure'
  db-express:
    image: mongo-express
    container_name: mongo-express-Strollin
    networks:
      - backend
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    restart: 'on-failure'
    depends_on:
      - db
  server:
    build: ./Strollin
    #image: server
    container_name: server-Strollin
    networks:
      - backend
    ports:
      - "3004:3004"
    restart: 'on-failure'
    depends_on:
      - db
      

networks:
  backend:
    # Use a custom driver which takes special options
    #driver: overlay
