name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd Strollin && npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Install npm dependencies
        run: |
          cd Strollin && npm install
      - name: Build Android Release
        run: |
          cd Strollin && cd android && ./gradlew assembleRelease
      - name: upload artifact to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
            appId: testdatareactnative
            token: 1//03nziq7GIIRP8CgYIARAAGAMSNwF-L9IrbkvGH2ToYbSb8X3fawDdqpIfNoIHM18R1fBlvmPnPsgXip8sAyPhN7cGdGnibRR9wIA
            groups: beta
            file: Strollin/android/app/build/outputs/apk/release/Strollin-release.apk
